### ISSUE TITLE
Add multiple local agents support

### ISSUE THREAD

**Issue by pjcuadra** [iotbzh/xds-server#1]
As a user I'd like to use the same `xds-server` to build multiple projects from multiple `xds-agent`s.

I'm currently setting a docker with `xds-server` in our internal infrastructure and it will be really good if we can share the same build server (`xds-server`) within multiple projects/users.

This might also be implemented by moving the `Global Configuration` to each projects' configuration.

**Comment by sebd71** [comment]
Hello,
The "Global Configuration" is already agent/client specific. So there is no need (and that doesn't make sens) to move "Global Configuration" settings to each projects.
I have no yet tested multiple xds-agent connected to one xds-server but I don't see any restriction to do that.
Would you please tell me more about what problem you are facing ?

**Comment by pjcuadra** [comment]
You are right. I could check it. I though that the project were available for everyone on the server side. Now with your comment I tested and it's actually agent-wise.
